version: "3"
services: 
  nginx: 
    image: nginx:stable-alpine
    ports: 
      - "3000:80"
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    # depends_on: 
    #   - node-app
  node-app:
    build: .
    # ports:
    #   - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules #anonymous volume - it helps overwritting if you delete node_modules file in local machine
    environment:
      - PORT=3000
      - MONGO_USER=yash
      - MONGO_PASSWORD=yash
      - SESSION_SECRET=secret
    # env_file: 
    #   - ./.env
    depends_on: 
      - mongo

  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=yash
      - MONGO_INITDB_ROOT_PASSWORD=yash
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis

volumes:
  mongo-db: